### ISSUE TITLE
How do I do feature extraction part?

### ISSUE THREAD

**Issue by TanmDL** [csinva/gan-pretrained-pytorch#1]
Thank you sharing the code.
In the feature extraction part, how did they get 28672 dimensional vector by using 4*4 spatial grid? What will be the input image size? Please help me to figure out this.

**Comment by csinva** [comment]
Hello, if you just want to understand the size for the input images, take a look at the notebooks which describe loading/running the models (example ![here](https://github.com/csinva/pytorch_gan_pretrained/blob/master/cifar10/dcgan_cifar10_pretrained_load.ipynb)).

If you want to understand the feature extraction, I recommend looking at the model class itself and printing out the shapes after each layer.

I've updated the readme a little to be more clear. Hope this helps!
